### ISSUE TITLE
Show whether or not something is the latest version in frameworks

### ISSUE THREAD

**Issue by xtinah-w** [Microsoft/WebTemplateStudio#1006]
(Latest) should be shown beside the version number to let user know whether or not this is the latest

**Comment by mcmxcdev** [comment]
@Tanya0609 I would like to work on this.

For all the javascript frameworks, it would be possible to check the latest stable version on npm with e.g: https://github.com/sindresorhus/latest-version and then compare it to the version used in the wizard.

I tried it out quickly but wasn't able to make a simple http request in the class `SelectFrontEndFramework`, maybe async/await is not supported? Or do you generally don't support http requests yet since I also found a `mockVsCodeApi` file?

Other suggestions to solve this are welcome of course.

**Comment by dgomezc** [comment]
Verified in dev-nightly ;
Templates version: 0.1.20052.2
Wizard version: 0.1.2005202
