### ISSUE TITLE
Python installation not detected

### ISSUE THREAD

**Issue by RohanGautam** [Microsoft/WebTemplateStudio#1150]
Python is not detected, and I get an error: `Error Generating templates`. The folder created by Web Template studio doesn't work when I run it because of this.

![Screenshot from 2019-08-25 15-57-28](https://user-images.githubusercontent.com/17317792/63647266-13348c00-c751-11e9-83ec-5b311c82bf4a.png)

![Screenshot from 2019-08-25 15-59-26](https://user-images.githubusercontent.com/17317792/63647284-57279100-c751-11e9-9a72-b3ddaa63d1d2.png)

**Comment by SahilTara** [comment]
Thank you so much for reporting this! Will look into this today!

**Comment by SahilTara** [comment]
Yeah definitely thanks for reporting, turns out the version of anaconda you're using reports to stderr instead of stdout. This could be fixed on your side by upgrading to a newer version of Anaconda, but we say that we support Python 3.5+ so we shouldn't force the user to upgrade. So my latest PR introduces a fix. I will let you know once the PR goes to the production extension!

**Comment by RohanGautam** [comment]
I see. Thanks for your time!!😊
