### ISSUE TITLE
Web Template Studio Launch does not work in Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by AndreeWille** [Microsoft/WebTemplateStudio#1166]
Repro steps:

1. Press Ctrl + Shift + p (in VS Code on Windows 10 using WSL Remote Extension in order to execute the command in WSL)
2. Execute Web Template Studio: Launch

Action: Sync-Engine
Error type: Error
Error Message: Could not sync to template repository

Version: 0.0.1922901
OS: linux (Ubuntu for Windows Subsystem for Linux)
VS Code Version: 1.37.1

<details>
<summary>Call Stack</summary>

```
LaunchExperience.<anonymous> (/home/<user>/.vscode-server/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1922901/out/launchExperience.js:40:23)
Generator.next (<anonymous>)
fulfilled (/home/<user>/.vscode-server/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1922901/out/launchExperience.js:4:58)
```

</details>

**Comment by Tanya0609** [comment]
Hi @AndreeWille, thanks for reporting. This is the same issue as #601.  
This issue may caused by file permission on your laptop, could you go through the following self-diagnose steps to see if the problem can be solved?

**1. Do you see any logs in the folder "/Users/[username]/.local/share/WebTS/Logs"? The path is %LocalAppData%\WebTs\Logs for windows. It is a hidden file. Could you share them?**

**2. /Users/[username]/.local/share/WebTS/ is the folder where templates are synchronized. Does your user have write permissions on /Users/[username]/.local/share?**

3. If you have the permission, you could create the folder manually. `mkdir -p ~/.local/share/WebTS` and restart VS Code. 

Then it should work for you. Please let me know if you have any more question!

**Comment by AndreeWille** [comment]
Hi @Tanya0609, thank you for anwering my report so quickly.

My user has write permissions to this folder.

After restarting Visual Studio Code it worked. To me it seems as this has also been logged. See attached logfile from .local/share/WebTS/Logs.

[WTS_Dev_20190829.log](https://github.com/microsoft/WebTemplateStudio/files/3558916/WTS_Dev_20190829.log)


i will be happy to answer further questions.

**Comment by SahilTara** [comment]
![Screenshot_20190830-102919](https://user-images.githubusercontent.com/32103099/64028705-20ff5e00-cb11-11e9-855d-42740fba5573.jpg)

Seems like it is a permissions issue. Possibly could be solved by using fallback directories or something for first time users.

**Comment by sibille** [comment]
Is this still an issue? 
	
Were missing permissions on 
	
```
Mac: /Users/[username]/.local/share
Linux: //home/[username]/.local/share
Windows:  %LocalAppData%
```
	
the underlying reason or did you have to change anything else?
	
Opened issue https://github.com/microsoft/WebTemplateStudio/issues/1182 to improve user feedback.

**Comment by AndreeWille** [comment]
I didn't change anything. My user had write access to this folder and the folder was present. It worked after restarting Visual Studio Code.

Unfortunately i can't give more information.
