### ISSUE TITLE
Change SampleData model's _id property to id

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1469]
We should change the SampleData model's _id to id and use a guid instead of an integer value.
This makes autogeneration easier and ensures unique ids. It also helps as signature between database and code is the same.

**Comment by dgomezc** [comment]
Hi @AndreMaz, we have problems to convert _id to id property with moleculer-db-adapter-mongo. 

Currently to get listitems we use: 

```
listGet: {
      rest: "GET /list",
      handler(ctx) {
        // Call find method that was loaded with `db.mixin.js`
        return this._find(ctx, ctx.params);
      }
    },
```
Is there way to configure MongoAdapter to convert _id to id in the _find function response?

**Comment by AndreMaz** [comment]
Hi @dgomezc yes, it is possible to convert `_id` to `id`

I can't do a PR because I'm getting an error when I run `./build-all.sh`
![image](https://user-images.githubusercontent.com/9802754/83898493-e33dfe80-a74e-11ea-834c-fb80fa8f4e53.png)

Anyway, in order to convert `_id` to `id` you need to set the `idField` in the settings of a service.
Here's an example. (It's NeDB but it also works for Mongo)
![image](https://user-images.githubusercontent.com/9802754/83899344-3795ae00-a750-11ea-9d38-ae43ea7a8d18.png)

You can set `idField` to anything you want and it will transform Mongo `_id`'s into the value of the `idField`.

Another solution is to wait for the DB results and transform the ids manually.
```js
listGet: {
      rest: "GET /list",
      async handler(ctx) {
        // Call find method that was loaded with `db.mixin.js`
        let results = await this._find(ctx, ctx.params);
        // Transform the "_ids" into "ids"
       return results
      }
    },
```

**Comment by sibille** [comment]
@andremaz, thanks for your help! About the error executing ./build-all.sh, is this the only error or are there more errors when builing the client? Seems as if the client build failed previously so the extension cannot find the manifest. Could you execute the script  ./build-client.sh to see if there are any errors here?

**Comment by AndreMaz** [comment]
Glad to help @sibille

Regarding the error, this is the output of `./build-client.sh`
![image](https://user-images.githubusercontent.com/9802754/84029250-ff79af80-a989-11ea-9d77-bf2007b896ca.png)

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.3.20195.1
Wizard version: 0.3.2019501
