### ISSUE TITLE
Change generated web applications folder structure 

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1494]
We're looking into changing the folder structure of the web applications we generate to use separate folders for frontend and backend.
 
We've setup a sample project at https://github.com/dgomezc/StructureProposalApp and would love to get your feedback on this, to ensure what we generate works for everybody.
 
The idea is that each project lives in its own folder with it's own package.json or scripts. For deployment we'll create a third folder with the server and compiled frontend. We're also adding VSCode Tasks to install dependencies and start client and server concurrently or separately for development.
 
Questions:
	• Does this new structure match your needs or do you see any issues? 
	• Is there anything else we should add? (f. ex scripts)

For more info on the motivation for this propsal see #1209 and #1189

**Comment by AndreMaz** [comment]
Are you planning to add `e2e` tests? If so, where would you place them?

**Comment by sibille** [comment]
We're not actively working on adding e2e tests, but it's a good idea, will open an issue to add it in. We think e2e tests should be located in the front-end folder, that's where the angular-cli puts them and we think it makes sense as they test the frontend (integrated with the backend).

**Comment by marko-hologram** [comment]
I have few thoughts, I'll try to split them in categories like folders or files, depending on which part of the template I'm giving feedback for. I do like the idea of separate backend and frontend folders and generating build files into a third folder, but I do have some thoughts overall. I'll also address this from React perspective since the repo that's linked is a React project.

## Folders

Maybe renaming `/backEnd` to `/server` and `/frontEnd` to `/client`? I haven't actually seen that much camel cased folder names "out in the wild". And it also might look weird considering the fact that "arm-templates" is dash separated (kebab-case). Or if you really want to leave it as backend and frontend name in particular, I would suggest against camelCase possibly. (`/frontend`, `/backend`).

One thing also I've seen that one folder is named "Master_Detail" in "frontEnd/src/components". I also find this highly unusual since other folders in components folder are named with PascalCase (NavBar, WarningMessage). Usually React convention is PascalCase for component names and folder names as far as I've seen. I see that in a newly generated project that component is called MasterDetail, while in this example repo it's called Master_Detail. Also, I'm not sure if word "master" currently clashes with the fact you are trying to rename master branch to something else (https://github.com/microsoft/WebTemplateStudio/issues/1475), so maybe even renaming "MasterDetail" component is something to keep in mind.

Also, `/out` is supposed to be the production build folder, right? Maybe just rename this to "build" or "dist". I guess "build" might even be better than "dist" since it's more explicit that it's a build folder. "Dist" is short for "distributable" which might not be so obvious.

## Files

One thing that comes to mind is the `.jsx` extension. I see that you are trying to follow Create React App as a baseline and they don't use `.jsx` for newly generated project, they instead just use `.js`. Maybe you are in favor of `.jsx` because it's more explicit that the file is a React component, but considering the fact that React components are usually named with PascalCase, that already gives them some distinction.

Regarding constants.js, maybe instead of defining the object and then adding items to it using dot(`.`) notation, why not just create objects and then add them to the constants object. Or even better yet, just make each of those keys a separate object without using the main `CONSTANTS` object.

CURRENT WORK
```js
// Current implementation
const CONSTANTS = {};

CONSTANTS.ERROR_MESSAGE = {};
CONSTANTS.ERROR_MESSAGE.GRID_GET = "Request to get grid text failed:";
...
```

WITHOUT DOT NOTATION
```js
const ERROR_MESSAGE = {
  GRID_GET: "Request to get grid text failed:",
  LIST_DELETE: "Request to delete list item failed:",
  ...
};

const CONSTANTS = {
  ERROR_MESSAGE,
};
```

WITHOUT CONSTANTS OBJECT
```js
const ERROR_MESSAGE = {
  GRID_GET: "Request to get grid text failed:",
  LIST_DELETE: "Request to delete list item failed:",
  ...
};

const ENDPOINT = {
  GRID: "/api/grid",
  LIST: "/api/list",
  ...
};
```

Third solution seems best to me since you use the `ERROR_MESSAGE` or `ENDPOINT` object directly without having to do `CONSTANTS.SOMETHING` and the fact that variable names are all uppercase kinda suggests they are constants anyway. Even if my last proposed solution doesn't seem great to you, I would highly suggest thinking about "without dot notation" suggestion. To me personally it seems easier that you can just take a quick look at an object and see all the key/value pairs it has, without having to go line by line below and seeing what key/value pairs were added line by line using dot notation.

Unfortunately I don't have any feedback on the backend side of things since I'm a frontend developer, but I hope this brought you some value at least. Sorry if some of this stuff is maybe off topic since this is mostly focused on folder structure, but I just had some thoughts.

**Comment by sibille** [comment]
Great feeback @marko-hologram, thanks !
### Folders
We'll switch to lowercase for folder names as tyou suggested. 

#### client/server vs frontend/backend folder
There are different opinions on the team but in the end we were more inclined to frontend and backend folder names as this matches the frontendframework and backendframework from the wizard choice on step 2. 

#### arm-templates folder
We will maintain the - here for better readability.

#### out folder
This folder will contain the server files + compiled output from the client in a build folder. In case of ASP.NET the server will be compiled too. I think calling it build or dist could lead to confusion. What about publish?

### Files
I will open a separate issue for the react feeback so we can disuss those changes there.

**Comment by marko-hologram** [comment]
> There are different opinions on the team but in the end we were more inclined to frontend and backend folder names as this matches the frontendframework and backendframework from the wizard choice on step 2.

Yeah good point about matching with wizard choice names.

> #### out folder
> 
> This folder will contain the server files + compiled output from the client in a build folder. In case of ASP.NET the server will be compiled too. I think calling it build or dist could lead to confusion. What about publish?

Publish seems really good to me since in my opinion it still communicates in a nice way that those are production ready files/builds. Files that are ready to be published. `/out` can mean a lot of things such as being an output from some process or script which isn't necessarily a publish/build script.

> ### Files
> 
> I will open a separate issue for the react feeback so we can disuss those changes there.

Ok great! I'll maybe have some other feedback there, we'll see.

**Comment by sibille** [comment]
We've added mockups for all other frontend and backend frameworks at https://github.com/dgomezc/StructureProposalApp.
You can use Visual Studio Code Tasks to install dependencies, start the app locally and build and prepare a package to publish to Azure App Services.
Would love to hear your feedback on the new structure.

**Comment by prupipho** [comment]
Verified on nightly build:
Templates version: 0.3.20287.1
Wizard version: 0.3.2028701
