### ISSUE TITLE
Review and remove unused packages from client and extension

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1616]
We should review the client and extension for unused packages and remove them.

**Comment by prupipho** [comment]
After trying we are not 100% confident that it won´t cause any issues. After removing most of those packages some errors appeared although we are not sure if they were there before.
We will only remove lodash for now because we tracked history and we are sure that is not currently used.

<img width="458" alt="client" src="https://user-images.githubusercontent.com/1333036/96997678-83e05f80-1532-11eb-851c-a53a2a3f6db5.png">
<img width="448" alt="extension" src="https://user-images.githubusercontent.com/1333036/96997680-8478f600-1532-11eb-8ab9-0bf161e37df6.png">
