### ISSUE TITLE
"Click here to skip" dialog in project creation does not work

### ISSUE THREAD

**Issue by JeanRoca** [Microsoft/WebTemplateStudio#1647]
**Describe the bug**
When creating a new project in the 4th step for "Add Optional Cloud Services" the top dialog that says "This step is optional click here to skip and create your project" does nothing.

**To Reproduce**
1. Create an app (I chose Angular/Node)
2. Advance to step 4
3. Try to click on the top banner to skip
4. Nothing happens

**Expected behavior**
The wizard should skip the step and create your project.

**Screenshots**
![image](https://user-images.githubusercontent.com/33772802/97229385-4a178f00-17a6-11eb-86c4-4db7e0dd87d5.png)

**Additional context**

**System**

- **VS Code Version:** 1.50.1
- **WebTS Wizard Version:** 0.4.2020202
- **WebTS Template Version:** ?
- **OS:** 19042.572

**Comment by sibille** [comment]
This was already fixed as part of #1579, which is assigned to the current milestone. 
The solution we took was to remove the blue banner, as this link is not needed anymore because the "Create Project" button is always available now and the banner felt very heavy.

To make clear that Azure Cloud Service configuration is optional we followed the design approach for WinTS for optional Azure Service Configuration. (https://github.com/microsoft/WindowsTemplateStudio/blob/dev/specs/resources/identity/UserNotLoggedIn.png)

This is what the page looks like in the nightly version:
![image](https://user-images.githubusercontent.com/24698018/97290076-5bb17300-1848-11eb-8c62-9aa3b880ce17.png)

As you can see we also added the option to sign in to Azure directly from this page (at the top right corner).
For milestone 0.6 we want to further improve the styling of this page #1577 and #1578.

**Comment by prupipho** [comment]
Already resolved on #1579
