### ISSUE TITLE
Add in Vue support

### ISSUE THREAD

**Issue by crutkas** [microsoft/WebTemplateStudio#199]

**Comment by SahilTara** [comment]
I can add this feature if need be, just assign it to me after mentioning me.

**Comment by crutkas** [comment]
if you want it, take it so it gets to feature parity of the React support

**Comment by SahilTara** [comment]
Okay cool I'll work on it this Friday, will be based off of https://github.com/microsoft/WebTemplateStudio/tree/t-kabail/vue-mocks

Would you want me to make it preview only like we've done with Angular?

**Comment by crutkas** [comment]
sure

**Comment by SahilTara** [comment]
@crutkas I have lined up PRs ( will come after merging of certain PRs but the branches are ready) for this issue can you add the in progress tag since I don't have permissions to do this anymore. :smile: Hope you're ready for vue! I have the preview tag on it for now, but I'm fairly certain that it will be at feature parity with react once all prs are in.  So once all PRs are in we will need to do a similar process to what we are doing with angular, and that is to verify we have feature parity and then turn the flag off.

**Comment by crutkas** [comment]
Will take a look today / tonight (on vacation 😁)

**Comment by SahilTara** [comment]
Oh oops did not read this message at all until now! Sorry, enjoy your vacation!

**Comment by crutkas** [comment]
who from the vue community has reviewed these?

**Comment by Tanya0609** [comment]
Since we have created another issue to log all the feedback from Vue experts and tracking the progress, thus closing this issue #978
