### ISSUE TITLE
Wizard: Merge front and backend together?

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WebTemplateStudio#597]
Are Front and and Backend so closely coupled that we should just have a "React + Node.JS" versus having them separate?  how often / scenarios where you'd do something different?

this would simplify the flow

**Comment by SahilTara** [comment]
No, the frontend and backend are barely coupled if anything. Node could be swapped with any backend, given that it gives the correct endpoints. React could be swapped with any frontend given that you spend the time to make the look and feel the same (As shown with angular).

Some possible scenarios: Angular + ASP.NET or Angular + Django. React + ASP.NET or React + Django. 

I think it wouldn't be wise to force additional coupling on the templates especially as we scale. I think both frameworks being on one page is good enough.

I think who ever mentioned the coupling was talking about our frontend templates requiring a backend of some kind (since they do calls to api endpoints). 

Hope this answers your question.

**Comment by AdrianoCahete** [comment]
A thing that you can do is to "pre-select" the backend option to match the "most common" frontend+backend choices. This will fulllfill the most common experiences, without change the currently behavior.

**Comment by xtinah-w** [comment]
The current default choice is React + Node since we have currently taken out project type. This achieves the same purpose as this issue. We will also be introducing a quick start feature that will default to a front-end and back-end feature (which are the most commonly used frameworks). This seems to resolve this issue. Closing this.
