### ISSUE TITLE
Switch primary button from "Close Wizard" to "Open Project" on Generation Status modal

### ISSUE THREAD

**Issue by xtinah-w** [Microsoft/WebTemplateStudio#626]
Right now, the primary button once the template has been generated is "Close Wizard", but developers most likely want to open their project and close the wizard afterwards. 

Currently, closing the wizard literally just closes the wizard, leaving the user to navigate to their project.

Alternatively, what if the project just opened up and closed the wizard automatically upon template generation? Just a thought - Adobe Creative Suite does this once the user inputs their specifications for their file/template type.

**Comment by ngkelly3** [comment]
One reason you might not want to close the wizard automatically is because Azure services may be deploying depending on what the developer selected, even though templates have already generated. There is also an "Open Project" button so that the developer does not need to navigate to the project themselves, along with the "Close Wizard" button - but to be clear, you are thinking of making "Open Project" the primary button?

**Comment by jsondoo** [comment]
> you are thinking of making "Open Project" the primary button?

Yes, this is what we want to change

> Azure services may be deploying depending on what the developer selected, even though templates 
have already generated

That's good to know 👍

**Comment by xtinah-w** [comment]
Feature is in Web Template Studio. Going to close this issue.
