### ISSUE TITLE
React NavBar component using anchor tags instead of React Router Links

### ISSUE THREAD

**Issue by scott-ammon** [Microsoft/WebTemplateStudio#641]
The NavBar component is using anchor tags as navigation aids to the different pages, which forces unnecessary page refreshes. Using React Router's built-in Link component would be a simple fix for this. I'd be happy to update this if it's the best path forward!

**Comment by SahilTara** [comment]
I would say go for it. It shouldn't be too hard and it will give exposure. I would recommend waiting until the two dll prs go in because currently testing template changes locally is a rough process. Those prs will make it much easier, "change the template hit f5 and generate". The unnecessary refresh when on the same page is a good catch though.

**Comment by scott-ammon** [comment]
Sounds good, thanks. I'll wait until those PRs are merged in.

**Comment by SahilTara** [comment]
If you are on windows/mac you are good to go! Linux should be in later today hopefully.
