### ISSUE TITLE
Resource Group textbox text color

### ISSUE THREAD

**Issue by jasmingoh** [Microsoft/WebTemplateStudio#643]
1) Add an Azure resource (either Azure Functions or Cosmos DB)
2) In the pop up, in the the textbox under Resource Group, the text colour is very close to the background color (shown in the screenshot below)

![DESIGN SCREENSHOT](https://user-images.githubusercontent.com/20333350/58582652-044c4500-8207-11e9-87c0-a42dad055d21.png)

Would be awesome if there is more contrast between the text and background color.

**Comment by SahilTara** [comment]
Woah, never knew you could type in these and that was the default colour for typing. Nice catch!

**Comment by jasmingoh** [comment]
Just looked into this issue, seems like the text colour for the other textbox are very similar to the background colour too.

For "Create Function Application", please change the text colour in the textbox under Subscription, Resource Group, Location, Runtime Stack and Number of functions

For "Create Cosmos DV Account", please change the text colour in the textbox under Subscription, Resource Group, API and Loation.

**Comment by ngkelly3** [comment]
Great catch! To provide some context, the dropdowns were not originally meant to have text input, but we needed to do it in order to get an aria-label (I think) on it for accessibility. This is a limitation with React-Select, so the other option would be to use another package entirely if you don't want want the dropdowns to also be a text input.
