### ISSUE TITLE
Wrap React Navbar within BrowserRouter

### ISSUE THREAD

**Issue by streetcoder123** [Microsoft/WebTemplateStudio#698]
A recent change to fix the tests on generated React Application made BrowserRouter to to wrap the switch statement without covering the Navbar. Hence, the navbar lost the capacity to use React Router Links. The Browser Router needs to wrap Navbar component. Then, the test file will have to use the BrowserRouter wrapping manually to test the App component.

**Comment by ngkelly3** [comment]
I'm going to leave this here in case it's useful for anyone, the text below refers specifically to the client

~We had issues using BrowserRouter because the client is served statically through VSCode Webview API - hence why we used HashRouter. Make sure you do a quick test to make sure BrowserRouter is feasible here - and great if you can get it working!~

**Comment by SahilTara** [comment]
@ngkelly3 I think he means for the generated code

**Comment by ngkelly3** [comment]
> @ngkelly3 I think he means for the generated code

Ah, that makes sense :)

**Comment by ngkelly3** [comment]
@njindal239 can you label this as "Generated Code"? If the team puts the "client" label on anything I can always chime in with my unsolicited 2 cents 😄

**Comment by streetcoder123** [comment]
@ngkelly3 Did it. Sorry for the confusion :D
