### ISSUE TITLE
Flask - cannot start application on Windows

### ISSUE THREAD

**Issue by jasmingoh** [Microsoft/WebTemplateStudio#797]
To reproduce: (on dev branch)
Install python 2.7 and 3.7 on your computer
Create a Flask application on Windows
In the generated application, run `yarn install` and `yarn start`

Note: `py -3` command works
![image](https://user-images.githubusercontent.com/20333350/60142305-048c2180-976e-11e9-9254-b2d7d09859c0.png)

![image](https://user-images.githubusercontent.com/20333350/60142277-ea524380-976d-11e9-9b2c-38debf6addaa.png)

**Comment by jsondoo** [comment]
Was this happening on dev or #792 ? 

It seems like it's working for me on both without any errors

**Comment by jasmingoh** [comment]
@jsondoo it happens when I was on this branch: garage/t-nijind/varFuncNames

Just tested on the dev branch, seems like it is only happening when I select other pages (e.g. list, master detail and grid)
![image](https://user-images.githubusercontent.com/20333350/60162787-117d3500-97af-11e9-9c85-5e1ff35495c7.png)

**Comment by jsondoo** [comment]
@jasmingoh I gave dev a try again, and it works with adding list items, grid, master details. I tried with python 3.7 with Cosmos MongoDB

**Comment by streetcoder123** [comment]
@jsondoo  As discussed with @jasmingoh, the problem seems to be occurring if the user has both Python 2 and Python 3 installed. In this case, `python` command is defaulted to python version 2. To run version 3, you need to run python launcher `py -3`. 
A simple solution would be to add another script for booting up python server through python launcher but that now looks to me like a hack.
We need to come up with a more generalized solution.
