### ISSUE TITLE
cannot launch, "Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/WebTemplateStudio#955]
when i run the `Web Template Studio: Launch...` command I get the following output:

![image](https://user-images.githubusercontent.com/1487073/61895427-81bec980-aec7-11e9-88eb-56e10616eb3b.png)

to repro:

browse to extension in the marketplace
click on "install"
VS code (stable) opens, install extension
press `F1` to open the command palette
choose `Web Template Studio: Launch" command

if I reload VS Code and try again, I get the same set of errors in the Output but i do see the editor open inside VS code.

**Comment by Tanya0609** [comment]
Could I ask: What operating system were you using? What was the version number?

What sync does is to look at a specific folder in your laptop, and copy/sync the templates data from WebTS into the folder. There maybe few reasons this error happening:
1. it could not find such folder
2. the connection to WebTS server did not response

We are in the middle of migrating our WebTS server from one to the other, that will help eliminate one of the potential cause 2. Cause 1 may happen due to different operating systems.

**Comment by chrisdias** [comment]
![image](https://user-images.githubusercontent.com/1487073/61901913-bdf92680-aed5-11e9-8a51-f3798cdedb93.png)

**Comment by jsondoo** [comment]
This issue should be fixed with #916
